# Generated by Django 5.2.16 on 2026-09-16 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_item_add_restriction_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('signed', 'Signed'), ('declined', 'Declined')], default='waiting', help_text='Current status of the sign request.', max_length=20)),
                ('zone_x', models.FloatField(help_text='X coordinate of the signature zone in percentage.')),
                ('zone_y', models.FloatField(help_text='Y coordinate of the signature zone in percentage.')),
                ('zone_width', models.FloatField(help_text='Width of the signature zone in percentage.')),
                ('zone_height', models.FloatField(help_text='Height of the signature zone in percentage.')),
                ('zone_page', models.IntegerField(help_text='0-indexed page number where the zone is placed.')),
                ('copy_item', models.ForeignKey(help_text='The spawned copy dedicated to the signer.', on_delete=django.db.models.deletion.CASCADE, related_name='sign_request_as_copy', to='core.item')),
                ('issuer', models.ForeignKey(help_text='The user who created this sign request.', on_delete=django.db.models.deletion.CASCADE, related_name='issued_sign_requests', to=settings.AUTH_USER_MODEL)),
                ('original_item', models.ForeignKey(help_text='The original item that was requested to be signed.', on_delete=django.db.models.deletion.CASCADE, related_name='sign_requests_as_original', to='core.item')),
                ('signer', models.ForeignKey(help_text='The user who is requested to sign the copy.', on_delete=django.db.models.deletion.CASCADE, related_name='sign_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sign Request',
                'verbose_name_plural': 'Sign Requests',
                'db_table': 'drive_sign_request',
            },
        ),
    ]
